name: CI-test
on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  woekflow_dispatch:

jobs: 
  eslint: 
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install packages
        run: npm ci

      - name: Run ESlint
        run: npm run ci:lint

      - name: Run tests
        run: npm run ci:test

      - name: Build
        run: npm run ci:build